spring.application.name=restaurante-rayocontrol-ga7-aa3-ev01
debug=false
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/rayocontrol_db
spring.datasource.username=postgres
spring.datasource.password=colombia
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO